with-expecter: true
inpackage: true
dir: "{{.InterfaceDirRelative}}"
mockname: "Mockery_{{.InterfaceName}}"
outpkg: "{{.InterfaceDirRelative}}"
filename: "mock_{{.InterfaceName}}.go"
packages:
    github.com/isabellecostawex/ps-tag-onboarding-go/internal/services:
        interfaces:
            UserManagementService:
                config:
                    inpackage: false
                    dir: internal/services/mocks
                    outpkg: mocks