with-expecter: true
inpackage: false
dir: internal/mocks
mockname: "Mock_{{.InterfaceName}}"
outpkg: mocks
filename: "mock_{{.InterfaceName}}.go"
packages:
    github.com/isabellecostawex/ps-tag-onboarding-go/internal/domain/users:
        interfaces:
            UsersRepository:
                config:
                    inpackage: false
                    dir: internal/mocks
                    outpkg: mocks
                    