with-expecter: true
inpackage: true
dir: "{{.InterfaceDirRelative}}"
mockname: "Mock_{{.InterfaceName}}"
outpkg: "{{.InterfaceDirRelative}}"
filename: "mock_{{.InterfaceName}}.go"
packages:
    github.com/isabellecostawex/ps-tag-onboarding-go/internal/domain/users:
        interfaces:
            UsersRepository:
